data = {
    'text': [
        # Politics
        'Political news about the election and upcoming debates',
        'Government policies and new political reforms',
        'Political unrest in various countries around the world',
        'Political debates on climate change policies',
        'Political tensions rising in Eastern Europe',
        'New immigration policies and their impact on society',
        'Elections results and their global implications',
        'International diplomatic relations and agreements',
        'Impact of the new electoral laws on the upcoming elections',
        'Analysis of recent political reforms in Latin America',
        'Political conflicts in the Middle East and their global repercussions',
        'Debates on public health and social security policies',
        'Debate on new data protection laws in Europe',
        'Impact of electoral reforms on upcoming local elections',
        'Foreign policy of emerging countries and its global influence',
        'Analysis of equality and human rights policies in different countries',

        # Economy
        'Economic news focusing on stock market fluctuations',
        'Latest updates on inflation rates and economic growth',
        'New developments in the tech industry and economy',
        'Economic impact of new trade agreements and tariffs',
        'Analysis of the global financial crisis and recovery',
        'Trends in real estate markets around the world',
        'Impact of cryptocurrency on traditional financial systems',
        'The role of central banks in economic stability',
        'Economic outlook for the next year in emerging markets',
        'Evolution of the labor market in the digital age',
        'Economic challenges in the transition to green economies',
        'Impact of the trade war on global supply chains',
        'Evolution of the cryptocurrency market and its regulation',
        'Trends in international trade and trade agreements',
        'Impact of artificial intelligence on the financial sector',
        'Growth prospects in emerging markets post-pandemic',

        # Sports
        'Sports news about the recent football championship',
        'Football match results and player statistics',
        'Sports highlights from recent international tournaments',
        'Sports news on recent victories and losses in major leagues',
        'Olympic Games updates and medal standings',
        'In-depth analysis of top athletes and their performances',
        'Controversies and scandals in the sports world',
        'The impact of sports on youth and education',
        'Preparations for the upcoming Olympic Games',
        'Analysis of changes in international sports rules',
        'Impact of star players’ injuries on teams',
        'Trends in women’s sports and its growing visibility',
        'Changes in rules of international tennis tournaments',
        'The rise of esports and its growing popularity',
        'Impact of sponsorships on athlete performance',
        'Development and preparation of new athletic prospects',

        # Health
        'Health tips and updates on medical research',
        'New advancements in medical treatments and technology',
        'Nutrition and wellness advice for a healthier lifestyle',
        'Updates on public health policies and initiatives',
        'The global response to pandemics and disease outbreaks',
        'Mental health awareness and the importance of support',
        'Innovations in healthcare technology and telemedicine',
        'The impact of diet and exercise on long-term health',
        'Investigations into new vaccines and treatments for infectious diseases',
        'Strategies to improve mental health in the workplace',
        'The role of telemedicine in primary health care',
        'Trends in the treatment of chronic diseases and their evolution',
        'Advancements in cancer research and new treatments',
        'Impact of the pandemic on mental health and support strategies',
        'New technologies in medical diagnosis and their accuracy',
        'Trends in nutrition and chronic disease prevention',

        # Entertainment
        'Entertainment news about upcoming movies and shows',
        'Celebrity gossip and entertainment industry updates',
        'Reviews and previews of new TV shows and films',
        'Trends in the entertainment industry and popular culture',
        'The rise of streaming platforms and their impact on cinema',
        'Music awards and performances of the year',
        'The influence of social media on celebrity culture',
        'Documentaries shedding light on global issues',
        'New streaming platforms and their influence on the entertainment industry',
        'The future of video games and virtual reality in entertainment',
        'Impact of live events and concerts on the music industry',
        'Analysis of new narratives in TV series and films',
        'Impact of streaming platforms on film production',
        'Analysis of recent trends in the video game industry',
        'Return of popular franchises and their reception by the public',
        'New trends in fashion and entertainment',

        # Crime
        'Crime reports and investigations on recent incidents',
        'Major criminal investigations and public safety updates',
        'High-profile legal cases and court rulings',
        'Community responses to recent criminal activities',
        'Rising crime rates in urban areas and preventive measures',
        'Cybersecurity threats and data breaches in major companies',
        'Human trafficking and efforts to combat it',
        'The role of law enforcement in maintaining public safety',
        'Changes in legislation on cyber crimes',
        'Investigations into financial frauds and scams',
        'Corruption cases in high positions and their impact on politics',
        'Community responses to natural disasters and emergencies',
        'New techniques in cyber crime investigation',
        'Increase in violence in conflict zones and its causes',
        'Development of new strategies in urban crime prevention',
        'Investigations into drug trafficking and its social impact',

        # Environment
        'Environmental issues and new sustainability initiatives',
        'Conservation efforts and wildlife protection updates',
        'Climate change impact and environmental policy news',
        'Innovations in eco-friendly technologies and practices',
        'The impact of deforestation on global ecosystems',
        'Efforts to reduce plastic waste in oceans',
        'Renewable energy sources and their future prospects',
        'The role of governments in combating climate change',
        'Innovations in waste management and recycling',
        'Reforestation projects and their impact on biodiversity',
        'Strategies to mitigate climate change effects in cities',
        'Challenges and solutions in water resource conservation',
        'Innovative projects in ocean preservation and marine life',
        'Impact of governmental policies on environmental protection',
        'New technologies for reducing carbon emissions',
        'Global initiatives for endangered species conservation',

        # Music
        'Music reviews and concert news',
        'Latest music album releases and artist news',
        'Trends in different music genres and emerging artists',
        'Interviews with musicians and insights into their work',
        'The influence of music on cultural movements',
        'Music festivals and their global impact',
        'The role of technology in modern music production',
        'Collaborations between artists from different genres',
        'Evolution of music genres in the past decade',
        'International collaborations in music production',
        'Impact of technology on music distribution',
        'Analysis of changes in online music consumption',
        'Cultural influences on the evolution of recent music genres',
        'Impact of social media on musicians careers',
        'New international artist collaborations and their impact',
        'Trends in music production and use of innovative software',

        # Social Media
        'Social media trends and viral content',
        'Impact of social media on public opinion and behavior',
        'Updates on major social media platforms and features',
        'Analysis of social media campaigns and their effectiveness',
        'The rise of influencers and their impact on marketing',
        'Privacy concerns and data security on social platforms',
        'The role of social media in political movements',
        'The evolution of communication in the digital age',
        'Studies on the effect of social media on mental health',
        'Development of new analytical tools for social media',
        'Impact of social media on politics and activism',
        'Trends in social media use among different demographic groups',
        'Effect of social media on politics and democracy',
        'Evolution of digital marketing strategies on social platforms',
        'Influence of social media on public perception of events',
        'Challenges and opportunities in moderating social media content'
    ],
    'category': [
        # Politics
        'politics', 'politics', 'politics', 'politics',
        'politics', 'politics', 'politics', 'politics',
        'politics', 'politics', 'politics', 'politics',
        'politics', 'politics', 'politics', 'politics',

        # Economy
        'economy', 'economy', 'economy', 'economy',
        'economy', 'economy', 'economy', 'economy',
        'economy', 'economy', 'economy', 'economy',
        'economy', 'economy', 'economy', 'economy',

        # Sports
        'sports', 'sports', 'sports', 'sports',
        'sports', 'sports', 'sports', 'sports',
        'sports', 'sports', 'sports', 'sports',
        'sports', 'sports', 'sports', 'sports',

        # Health
        'health', 'health', 'health', 'health',
        'health', 'health', 'health', 'health',
        'health', 'health', 'health', 'health',
        'health', 'health', 'health', 'health',

        # Entertainment
        'entertainment', 'entertainment', 'entertainment', 'entertainment',
        'entertainment', 'entertainment', 'entertainment', 'entertainment',
        'entertainment', 'entertainment', 'entertainment', 'entertainment',
        'entertainment', 'entertainment', 'entertainment', 'entertainment',

        # Crime
        'crime', 'crime', 'crime', 'crime',
        'crime', 'crime', 'crime', 'crime',
        'crime', 'crime', 'crime', 'crime',
        'crime', 'crime', 'crime', 'crime',

        # Environment
        'environment', 'environment', 'environment', 'environment',
        'environment', 'environment', 'environment', 'environment',
        'environment', 'environment', 'environment', 'environment',
        'environment', 'environment', 'environment', 'environment',

        # Music
        'music', 'music', 'music', 'music',
        'music', 'music', 'music', 'music',
        'music', 'music', 'music', 'music',
        'music', 'music', 'music', 'music',

        # Social Media
        'social media', 'social media', 'social media', 'social media',
        'social media', 'social media', 'social media', 'social media',
        'social media', 'social media', 'social media', 'social media',
        'social media', 'social media', 'social media', 'social media'
    ]
}
